import { FormFieldInterface } from "lib/interfaces";

const fields: ReadonlyArray<FormFieldInterface> = [
  { id: 1, type: "title", text: "Название должности", isRequired: true },
  {
    id: 2,
    type: "text",
    name: "name",
    value: "",
    isError: false,
    isRequired: true,
    placeholder: "Оставить комментарий",
    errorText: "Пожалуйста укажите название должности",
  },
  { id: 3, type: "title", text: "Условия работы" },
  {
    id: 4,
    type: "city",
    name: "city",
    value: "",
    isRequired: true,
    isError: false,
    label: "Город работы",
    placeholder: "Город",
    errorText: "Пожалуйста укажите город работы",
  },
  {
    id: 5,
    type: "text",
    name: "address",
    value: "",
    isRequired: true,
    isError: false,
    label: "Адрес работы",
    placeholder: "Улица и дом",
    errorText: "Пожалуйста укажите адрес работы",
  },
  { id: 6, type: "title", text: "Зарплата", isRequired: true },
  {
    id: 7,
    type: "price",
    name: "price",
    from: "",
    to: "",
    one: "",
    message: "",
    rangeTitle: "Диапазон",
    oneTitle: "Одно значение",
    emptyTitle: "Не указывать",
    messageTitle: "Коментарий к зарплате",
    isRangeError: false,
    isOneError: false,
    placeholderFrom: "от",
    placeholderTo: "до",
    errorRangeText: "Пожалуйста укажите минимальное значение зарплаты",
    errorOneText: "Пожалуйста укажите значение зарплаты",
  },
];

export default fields;
